version: '3'

services:
  postgresql:
    image: postgres:13
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    command: postgres -N 500
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "root"
    ports:
      - 5433:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql